/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedEtudiantRouteImport } from './routes/_authenticated/etudiant'
import { Route as AuthenticatedConseillerRouteImport } from './routes/_authenticated/conseiller'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedEtudiantIndexRouteImport } from './routes/_authenticated/etudiant.index'
import { Route as AuthenticatedEtudiantDossierRouteImport } from './routes/_authenticated/etudiant.dossier'
import { Route as AuthenticatedEtudiantDocumentsRouteImport } from './routes/_authenticated/etudiant.documents'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEtudiantRoute = AuthenticatedEtudiantRouteImport.update({
  id: '/etudiant',
  path: '/etudiant',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConseillerRoute = AuthenticatedConseillerRouteImport.update({
  id: '/conseiller',
  path: '/conseiller',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEtudiantIndexRoute =
  AuthenticatedEtudiantIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEtudiantRoute,
  } as any)
const AuthenticatedEtudiantDossierRoute =
  AuthenticatedEtudiantDossierRouteImport.update({
    id: '/dossier',
    path: '/dossier',
    getParentRoute: () => AuthenticatedEtudiantRoute,
  } as any)
const AuthenticatedEtudiantDocumentsRoute =
  AuthenticatedEtudiantDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedEtudiantRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/app': typeof AuthenticatedAppRoute
  '/conseiller': typeof AuthenticatedConseillerRoute
  '/etudiant': typeof AuthenticatedEtudiantRouteWithChildren
  '/etudiant/documents': typeof AuthenticatedEtudiantDocumentsRoute
  '/etudiant/dossier': typeof AuthenticatedEtudiantDossierRoute
  '/etudiant/': typeof AuthenticatedEtudiantIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/app': typeof AuthenticatedAppRoute
  '/conseiller': typeof AuthenticatedConseillerRoute
  '/etudiant/documents': typeof AuthenticatedEtudiantDocumentsRoute
  '/etudiant/dossier': typeof AuthenticatedEtudiantDossierRoute
  '/etudiant': typeof AuthenticatedEtudiantIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/conseiller': typeof AuthenticatedConseillerRoute
  '/_authenticated/etudiant': typeof AuthenticatedEtudiantRouteWithChildren
  '/_authenticated/etudiant/documents': typeof AuthenticatedEtudiantDocumentsRoute
  '/_authenticated/etudiant/dossier': typeof AuthenticatedEtudiantDossierRoute
  '/_authenticated/etudiant/': typeof AuthenticatedEtudiantIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/unauthorized'
    | '/admin'
    | '/app'
    | '/conseiller'
    | '/etudiant'
    | '/etudiant/documents'
    | '/etudiant/dossier'
    | '/etudiant/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/unauthorized'
    | '/admin'
    | '/app'
    | '/conseiller'
    | '/etudiant/documents'
    | '/etudiant/dossier'
    | '/etudiant'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/unauthorized'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/conseiller'
    | '/_authenticated/etudiant'
    | '/_authenticated/etudiant/documents'
    | '/_authenticated/etudiant/dossier'
    | '/_authenticated/etudiant/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/etudiant': {
      id: '/_authenticated/etudiant'
      path: '/etudiant'
      fullPath: '/etudiant'
      preLoaderRoute: typeof AuthenticatedEtudiantRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/conseiller': {
      id: '/_authenticated/conseiller'
      path: '/conseiller'
      fullPath: '/conseiller'
      preLoaderRoute: typeof AuthenticatedConseillerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/etudiant/': {
      id: '/_authenticated/etudiant/'
      path: '/'
      fullPath: '/etudiant/'
      preLoaderRoute: typeof AuthenticatedEtudiantIndexRouteImport
      parentRoute: typeof AuthenticatedEtudiantRoute
    }
    '/_authenticated/etudiant/dossier': {
      id: '/_authenticated/etudiant/dossier'
      path: '/dossier'
      fullPath: '/etudiant/dossier'
      preLoaderRoute: typeof AuthenticatedEtudiantDossierRouteImport
      parentRoute: typeof AuthenticatedEtudiantRoute
    }
    '/_authenticated/etudiant/documents': {
      id: '/_authenticated/etudiant/documents'
      path: '/documents'
      fullPath: '/etudiant/documents'
      preLoaderRoute: typeof AuthenticatedEtudiantDocumentsRouteImport
      parentRoute: typeof AuthenticatedEtudiantRoute
    }
  }
}

interface AuthenticatedEtudiantRouteChildren {
  AuthenticatedEtudiantDocumentsRoute: typeof AuthenticatedEtudiantDocumentsRoute
  AuthenticatedEtudiantDossierRoute: typeof AuthenticatedEtudiantDossierRoute
  AuthenticatedEtudiantIndexRoute: typeof AuthenticatedEtudiantIndexRoute
}

const AuthenticatedEtudiantRouteChildren: AuthenticatedEtudiantRouteChildren = {
  AuthenticatedEtudiantDocumentsRoute: AuthenticatedEtudiantDocumentsRoute,
  AuthenticatedEtudiantDossierRoute: AuthenticatedEtudiantDossierRoute,
  AuthenticatedEtudiantIndexRoute: AuthenticatedEtudiantIndexRoute,
}

const AuthenticatedEtudiantRouteWithChildren =
  AuthenticatedEtudiantRoute._addFileChildren(
    AuthenticatedEtudiantRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedConseillerRoute: typeof AuthenticatedConseillerRoute
  AuthenticatedEtudiantRoute: typeof AuthenticatedEtudiantRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedConseillerRoute: AuthenticatedConseillerRoute,
  AuthenticatedEtudiantRoute: AuthenticatedEtudiantRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
