/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedEtudiantRouteImport } from './routes/_authenticated/etudiant'
import { Route as AuthenticatedConseillerRouteImport } from './routes/_authenticated/conseiller'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedEtudiantIndexRouteImport } from './routes/_authenticated/etudiant.index'
import { Route as AuthenticatedConseillerIndexRouteImport } from './routes/_authenticated/conseiller.index'
import { Route as AuthenticatedEtudiantRendezVousRouteImport } from './routes/_authenticated/etudiant.rendez-vous'
import { Route as AuthenticatedEtudiantMessagesRouteImport } from './routes/_authenticated/etudiant.messages'
import { Route as AuthenticatedEtudiantDossierRouteImport } from './routes/_authenticated/etudiant.dossier'
import { Route as AuthenticatedEtudiantDocumentsRouteImport } from './routes/_authenticated/etudiant.documents'
import { Route as AuthenticatedConseillerValidationsRouteImport } from './routes/_authenticated/conseiller.validations'
import { Route as AuthenticatedConseillerRendezVousRouteImport } from './routes/_authenticated/conseiller.rendez-vous'
import { Route as AuthenticatedConseillerMessagesRouteImport } from './routes/_authenticated/conseiller.messages'
import { Route as AuthenticatedConseillerEtudiantsRouteImport } from './routes/_authenticated/conseiller.etudiants'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEtudiantRoute = AuthenticatedEtudiantRouteImport.update({
  id: '/etudiant',
  path: '/etudiant',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConseillerRoute = AuthenticatedConseillerRouteImport.update({
  id: '/conseiller',
  path: '/conseiller',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEtudiantIndexRoute =
  AuthenticatedEtudiantIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEtudiantRoute,
  } as any)
const AuthenticatedConseillerIndexRoute =
  AuthenticatedConseillerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedConseillerRoute,
  } as any)
const AuthenticatedEtudiantRendezVousRoute =
  AuthenticatedEtudiantRendezVousRouteImport.update({
    id: '/rendez-vous',
    path: '/rendez-vous',
    getParentRoute: () => AuthenticatedEtudiantRoute,
  } as any)
const AuthenticatedEtudiantMessagesRoute =
  AuthenticatedEtudiantMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedEtudiantRoute,
  } as any)
const AuthenticatedEtudiantDossierRoute =
  AuthenticatedEtudiantDossierRouteImport.update({
    id: '/dossier',
    path: '/dossier',
    getParentRoute: () => AuthenticatedEtudiantRoute,
  } as any)
const AuthenticatedEtudiantDocumentsRoute =
  AuthenticatedEtudiantDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedEtudiantRoute,
  } as any)
const AuthenticatedConseillerValidationsRoute =
  AuthenticatedConseillerValidationsRouteImport.update({
    id: '/validations',
    path: '/validations',
    getParentRoute: () => AuthenticatedConseillerRoute,
  } as any)
const AuthenticatedConseillerRendezVousRoute =
  AuthenticatedConseillerRendezVousRouteImport.update({
    id: '/rendez-vous',
    path: '/rendez-vous',
    getParentRoute: () => AuthenticatedConseillerRoute,
  } as any)
const AuthenticatedConseillerMessagesRoute =
  AuthenticatedConseillerMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedConseillerRoute,
  } as any)
const AuthenticatedConseillerEtudiantsRoute =
  AuthenticatedConseillerEtudiantsRouteImport.update({
    id: '/etudiants',
    path: '/etudiants',
    getParentRoute: () => AuthenticatedConseillerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/app': typeof AuthenticatedAppRoute
  '/conseiller': typeof AuthenticatedConseillerRouteWithChildren
  '/etudiant': typeof AuthenticatedEtudiantRouteWithChildren
  '/conseiller/etudiants': typeof AuthenticatedConseillerEtudiantsRoute
  '/conseiller/messages': typeof AuthenticatedConseillerMessagesRoute
  '/conseiller/rendez-vous': typeof AuthenticatedConseillerRendezVousRoute
  '/conseiller/validations': typeof AuthenticatedConseillerValidationsRoute
  '/etudiant/documents': typeof AuthenticatedEtudiantDocumentsRoute
  '/etudiant/dossier': typeof AuthenticatedEtudiantDossierRoute
  '/etudiant/messages': typeof AuthenticatedEtudiantMessagesRoute
  '/etudiant/rendez-vous': typeof AuthenticatedEtudiantRendezVousRoute
  '/conseiller/': typeof AuthenticatedConseillerIndexRoute
  '/etudiant/': typeof AuthenticatedEtudiantIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/app': typeof AuthenticatedAppRoute
  '/conseiller/etudiants': typeof AuthenticatedConseillerEtudiantsRoute
  '/conseiller/messages': typeof AuthenticatedConseillerMessagesRoute
  '/conseiller/rendez-vous': typeof AuthenticatedConseillerRendezVousRoute
  '/conseiller/validations': typeof AuthenticatedConseillerValidationsRoute
  '/etudiant/documents': typeof AuthenticatedEtudiantDocumentsRoute
  '/etudiant/dossier': typeof AuthenticatedEtudiantDossierRoute
  '/etudiant/messages': typeof AuthenticatedEtudiantMessagesRoute
  '/etudiant/rendez-vous': typeof AuthenticatedEtudiantRendezVousRoute
  '/conseiller': typeof AuthenticatedConseillerIndexRoute
  '/etudiant': typeof AuthenticatedEtudiantIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/conseiller': typeof AuthenticatedConseillerRouteWithChildren
  '/_authenticated/etudiant': typeof AuthenticatedEtudiantRouteWithChildren
  '/_authenticated/conseiller/etudiants': typeof AuthenticatedConseillerEtudiantsRoute
  '/_authenticated/conseiller/messages': typeof AuthenticatedConseillerMessagesRoute
  '/_authenticated/conseiller/rendez-vous': typeof AuthenticatedConseillerRendezVousRoute
  '/_authenticated/conseiller/validations': typeof AuthenticatedConseillerValidationsRoute
  '/_authenticated/etudiant/documents': typeof AuthenticatedEtudiantDocumentsRoute
  '/_authenticated/etudiant/dossier': typeof AuthenticatedEtudiantDossierRoute
  '/_authenticated/etudiant/messages': typeof AuthenticatedEtudiantMessagesRoute
  '/_authenticated/etudiant/rendez-vous': typeof AuthenticatedEtudiantRendezVousRoute
  '/_authenticated/conseiller/': typeof AuthenticatedConseillerIndexRoute
  '/_authenticated/etudiant/': typeof AuthenticatedEtudiantIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/unauthorized'
    | '/admin'
    | '/app'
    | '/conseiller'
    | '/etudiant'
    | '/conseiller/etudiants'
    | '/conseiller/messages'
    | '/conseiller/rendez-vous'
    | '/conseiller/validations'
    | '/etudiant/documents'
    | '/etudiant/dossier'
    | '/etudiant/messages'
    | '/etudiant/rendez-vous'
    | '/conseiller/'
    | '/etudiant/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/unauthorized'
    | '/admin'
    | '/app'
    | '/conseiller/etudiants'
    | '/conseiller/messages'
    | '/conseiller/rendez-vous'
    | '/conseiller/validations'
    | '/etudiant/documents'
    | '/etudiant/dossier'
    | '/etudiant/messages'
    | '/etudiant/rendez-vous'
    | '/conseiller'
    | '/etudiant'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/unauthorized'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/conseiller'
    | '/_authenticated/etudiant'
    | '/_authenticated/conseiller/etudiants'
    | '/_authenticated/conseiller/messages'
    | '/_authenticated/conseiller/rendez-vous'
    | '/_authenticated/conseiller/validations'
    | '/_authenticated/etudiant/documents'
    | '/_authenticated/etudiant/dossier'
    | '/_authenticated/etudiant/messages'
    | '/_authenticated/etudiant/rendez-vous'
    | '/_authenticated/conseiller/'
    | '/_authenticated/etudiant/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/etudiant': {
      id: '/_authenticated/etudiant'
      path: '/etudiant'
      fullPath: '/etudiant'
      preLoaderRoute: typeof AuthenticatedEtudiantRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/conseiller': {
      id: '/_authenticated/conseiller'
      path: '/conseiller'
      fullPath: '/conseiller'
      preLoaderRoute: typeof AuthenticatedConseillerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/etudiant/': {
      id: '/_authenticated/etudiant/'
      path: '/'
      fullPath: '/etudiant/'
      preLoaderRoute: typeof AuthenticatedEtudiantIndexRouteImport
      parentRoute: typeof AuthenticatedEtudiantRoute
    }
    '/_authenticated/conseiller/': {
      id: '/_authenticated/conseiller/'
      path: '/'
      fullPath: '/conseiller/'
      preLoaderRoute: typeof AuthenticatedConseillerIndexRouteImport
      parentRoute: typeof AuthenticatedConseillerRoute
    }
    '/_authenticated/etudiant/rendez-vous': {
      id: '/_authenticated/etudiant/rendez-vous'
      path: '/rendez-vous'
      fullPath: '/etudiant/rendez-vous'
      preLoaderRoute: typeof AuthenticatedEtudiantRendezVousRouteImport
      parentRoute: typeof AuthenticatedEtudiantRoute
    }
    '/_authenticated/etudiant/messages': {
      id: '/_authenticated/etudiant/messages'
      path: '/messages'
      fullPath: '/etudiant/messages'
      preLoaderRoute: typeof AuthenticatedEtudiantMessagesRouteImport
      parentRoute: typeof AuthenticatedEtudiantRoute
    }
    '/_authenticated/etudiant/dossier': {
      id: '/_authenticated/etudiant/dossier'
      path: '/dossier'
      fullPath: '/etudiant/dossier'
      preLoaderRoute: typeof AuthenticatedEtudiantDossierRouteImport
      parentRoute: typeof AuthenticatedEtudiantRoute
    }
    '/_authenticated/etudiant/documents': {
      id: '/_authenticated/etudiant/documents'
      path: '/documents'
      fullPath: '/etudiant/documents'
      preLoaderRoute: typeof AuthenticatedEtudiantDocumentsRouteImport
      parentRoute: typeof AuthenticatedEtudiantRoute
    }
    '/_authenticated/conseiller/validations': {
      id: '/_authenticated/conseiller/validations'
      path: '/validations'
      fullPath: '/conseiller/validations'
      preLoaderRoute: typeof AuthenticatedConseillerValidationsRouteImport
      parentRoute: typeof AuthenticatedConseillerRoute
    }
    '/_authenticated/conseiller/rendez-vous': {
      id: '/_authenticated/conseiller/rendez-vous'
      path: '/rendez-vous'
      fullPath: '/conseiller/rendez-vous'
      preLoaderRoute: typeof AuthenticatedConseillerRendezVousRouteImport
      parentRoute: typeof AuthenticatedConseillerRoute
    }
    '/_authenticated/conseiller/messages': {
      id: '/_authenticated/conseiller/messages'
      path: '/messages'
      fullPath: '/conseiller/messages'
      preLoaderRoute: typeof AuthenticatedConseillerMessagesRouteImport
      parentRoute: typeof AuthenticatedConseillerRoute
    }
    '/_authenticated/conseiller/etudiants': {
      id: '/_authenticated/conseiller/etudiants'
      path: '/etudiants'
      fullPath: '/conseiller/etudiants'
      preLoaderRoute: typeof AuthenticatedConseillerEtudiantsRouteImport
      parentRoute: typeof AuthenticatedConseillerRoute
    }
  }
}

interface AuthenticatedConseillerRouteChildren {
  AuthenticatedConseillerEtudiantsRoute: typeof AuthenticatedConseillerEtudiantsRoute
  AuthenticatedConseillerMessagesRoute: typeof AuthenticatedConseillerMessagesRoute
  AuthenticatedConseillerRendezVousRoute: typeof AuthenticatedConseillerRendezVousRoute
  AuthenticatedConseillerValidationsRoute: typeof AuthenticatedConseillerValidationsRoute
  AuthenticatedConseillerIndexRoute: typeof AuthenticatedConseillerIndexRoute
}

const AuthenticatedConseillerRouteChildren: AuthenticatedConseillerRouteChildren =
  {
    AuthenticatedConseillerEtudiantsRoute:
      AuthenticatedConseillerEtudiantsRoute,
    AuthenticatedConseillerMessagesRoute: AuthenticatedConseillerMessagesRoute,
    AuthenticatedConseillerRendezVousRoute:
      AuthenticatedConseillerRendezVousRoute,
    AuthenticatedConseillerValidationsRoute:
      AuthenticatedConseillerValidationsRoute,
    AuthenticatedConseillerIndexRoute: AuthenticatedConseillerIndexRoute,
  }

const AuthenticatedConseillerRouteWithChildren =
  AuthenticatedConseillerRoute._addFileChildren(
    AuthenticatedConseillerRouteChildren,
  )

interface AuthenticatedEtudiantRouteChildren {
  AuthenticatedEtudiantDocumentsRoute: typeof AuthenticatedEtudiantDocumentsRoute
  AuthenticatedEtudiantDossierRoute: typeof AuthenticatedEtudiantDossierRoute
  AuthenticatedEtudiantMessagesRoute: typeof AuthenticatedEtudiantMessagesRoute
  AuthenticatedEtudiantRendezVousRoute: typeof AuthenticatedEtudiantRendezVousRoute
  AuthenticatedEtudiantIndexRoute: typeof AuthenticatedEtudiantIndexRoute
}

const AuthenticatedEtudiantRouteChildren: AuthenticatedEtudiantRouteChildren = {
  AuthenticatedEtudiantDocumentsRoute: AuthenticatedEtudiantDocumentsRoute,
  AuthenticatedEtudiantDossierRoute: AuthenticatedEtudiantDossierRoute,
  AuthenticatedEtudiantMessagesRoute: AuthenticatedEtudiantMessagesRoute,
  AuthenticatedEtudiantRendezVousRoute: AuthenticatedEtudiantRendezVousRoute,
  AuthenticatedEtudiantIndexRoute: AuthenticatedEtudiantIndexRoute,
}

const AuthenticatedEtudiantRouteWithChildren =
  AuthenticatedEtudiantRoute._addFileChildren(
    AuthenticatedEtudiantRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedConseillerRoute: typeof AuthenticatedConseillerRouteWithChildren
  AuthenticatedEtudiantRoute: typeof AuthenticatedEtudiantRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedConseillerRoute: AuthenticatedConseillerRouteWithChildren,
  AuthenticatedEtudiantRoute: AuthenticatedEtudiantRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
