/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BlockedRouteImport } from './routes/blocked'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSecretaireRouteImport } from './routes/_authenticated/secretaire'
import { Route as AuthenticatedRhRouteImport } from './routes/_authenticated/rh'
import { Route as AuthenticatedProjetsRouteImport } from './routes/_authenticated/projets'
import { Route as AuthenticatedEtudiantRouteImport } from './routes/_authenticated/etudiant'
import { Route as AuthenticatedEcoleRouteImport } from './routes/_authenticated/ecole'
import { Route as AuthenticatedConseillerRouteImport } from './routes/_authenticated/conseiller'
import { Route as AuthenticatedComptabiliteRouteImport } from './routes/_authenticated/comptabilite'
import { Route as AuthenticatedCommercialRouteImport } from './routes/_authenticated/commercial'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedSecretaireIndexRouteImport } from './routes/_authenticated/secretaire.index'
import { Route as AuthenticatedRhIndexRouteImport } from './routes/_authenticated/rh.index'
import { Route as AuthenticatedProjetsIndexRouteImport } from './routes/_authenticated/projets.index'
import { Route as AuthenticatedEtudiantIndexRouteImport } from './routes/_authenticated/etudiant.index'
import { Route as AuthenticatedEcoleIndexRouteImport } from './routes/_authenticated/ecole.index'
import { Route as AuthenticatedConseillerIndexRouteImport } from './routes/_authenticated/conseiller.index'
import { Route as AuthenticatedComptabiliteIndexRouteImport } from './routes/_authenticated/comptabilite.index'
import { Route as AuthenticatedCommercialIndexRouteImport } from './routes/_authenticated/commercial.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedSecretaireValidationsRouteImport } from './routes/_authenticated/secretaire.validations'
import { Route as AuthenticatedSecretaireRendezVousRouteImport } from './routes/_authenticated/secretaire.rendez-vous'
import { Route as AuthenticatedSecretaireMessagesRouteImport } from './routes/_authenticated/secretaire.messages'
import { Route as AuthenticatedSecretaireEtudiantsRouteImport } from './routes/_authenticated/secretaire.etudiants'
import { Route as AuthenticatedSecretaireCourriersRouteImport } from './routes/_authenticated/secretaire.courriers'
import { Route as AuthenticatedSecretaireClientsRouteImport } from './routes/_authenticated/secretaire.clients'
import { Route as AuthenticatedRhRendezVousClientsRouteImport } from './routes/_authenticated/rh.rendez-vous-clients'
import { Route as AuthenticatedRhPersonnelRouteImport } from './routes/_authenticated/rh.personnel'
import { Route as AuthenticatedProjetsRendezVousClientsRouteImport } from './routes/_authenticated/projets.rendez-vous-clients'
import { Route as AuthenticatedProjetsListeRouteImport } from './routes/_authenticated/projets.liste'
import { Route as AuthenticatedEtudiantRendezVousRouteImport } from './routes/_authenticated/etudiant.rendez-vous'
import { Route as AuthenticatedEtudiantProfilRouteImport } from './routes/_authenticated/etudiant.profil'
import { Route as AuthenticatedEtudiantParcoursRouteImport } from './routes/_authenticated/etudiant.parcours'
import { Route as AuthenticatedEtudiantMessagesRouteImport } from './routes/_authenticated/etudiant.messages'
import { Route as AuthenticatedEtudiantEcolesRouteImport } from './routes/_authenticated/etudiant.ecoles'
import { Route as AuthenticatedEtudiantDossierRouteImport } from './routes/_authenticated/etudiant.dossier'
import { Route as AuthenticatedEtudiantDocumentsRouteImport } from './routes/_authenticated/etudiant.documents'
import { Route as AuthenticatedEtudiantCandidaturesRouteImport } from './routes/_authenticated/etudiant.candidatures'
import { Route as AuthenticatedEcoleFormationsRouteImport } from './routes/_authenticated/ecole.formations'
import { Route as AuthenticatedEcoleCandidatsRouteImport } from './routes/_authenticated/ecole.candidats'
import { Route as AuthenticatedConseillerValidationsRouteImport } from './routes/_authenticated/conseiller.validations'
import { Route as AuthenticatedConseillerRendezVousClientsRouteImport } from './routes/_authenticated/conseiller.rendez-vous-clients'
import { Route as AuthenticatedConseillerRendezVousRouteImport } from './routes/_authenticated/conseiller.rendez-vous'
import { Route as AuthenticatedConseillerMessagesRouteImport } from './routes/_authenticated/conseiller.messages'
import { Route as AuthenticatedConseillerEtudiantsRouteImport } from './routes/_authenticated/conseiller.etudiants'
import { Route as AuthenticatedComptabiliteTransactionsRouteImport } from './routes/_authenticated/comptabilite.transactions'
import { Route as AuthenticatedComptabiliteRendezVousClientsRouteImport } from './routes/_authenticated/comptabilite.rendez-vous-clients'
import { Route as AuthenticatedCommercialRendezVousClientsRouteImport } from './routes/_authenticated/commercial.rendez-vous-clients'
import { Route as AuthenticatedCommercialActivitesRouteImport } from './routes/_authenticated/commercial.activites'
import { Route as AuthenticatedAdminValidationsRouteImport } from './routes/_authenticated/admin.validations'
import { Route as AuthenticatedAdminUtilisateursRouteImport } from './routes/_authenticated/admin.utilisateurs'
import { Route as AuthenticatedAdminRendezVousClientsRouteImport } from './routes/_authenticated/admin.rendez-vous-clients'
import { Route as AuthenticatedAdminRendezVousRouteImport } from './routes/_authenticated/admin.rendez-vous'
import { Route as AuthenticatedAdminMessagesRouteImport } from './routes/_authenticated/admin.messages'
import { Route as AuthenticatedAdminEcolesRouteImport } from './routes/_authenticated/admin.ecoles'
import { Route as AuthenticatedAdminDossiersRouteImport } from './routes/_authenticated/admin.dossiers'
import { Route as AuthenticatedSecretaireEtudiantsIndexRouteImport } from './routes/_authenticated/secretaire.etudiants.index'
import { Route as AuthenticatedConseillerEtudiantsIndexRouteImport } from './routes/_authenticated/conseiller.etudiants.index'
import { Route as AuthenticatedSecretaireEtudiantsStudentIdRouteImport } from './routes/_authenticated/secretaire.etudiants.$studentId'
import { Route as AuthenticatedConseillerEtudiantsStudentIdRouteImport } from './routes/_authenticated/conseiller.etudiants.$studentId'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BlockedRoute = BlockedRouteImport.update({
  id: '/blocked',
  path: '/blocked',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSecretaireRoute = AuthenticatedSecretaireRouteImport.update({
  id: '/secretaire',
  path: '/secretaire',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRhRoute = AuthenticatedRhRouteImport.update({
  id: '/rh',
  path: '/rh',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjetsRoute = AuthenticatedProjetsRouteImport.update({
  id: '/projets',
  path: '/projets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEtudiantRoute = AuthenticatedEtudiantRouteImport.update({
  id: '/etudiant',
  path: '/etudiant',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEcoleRoute = AuthenticatedEcoleRouteImport.update({
  id: '/ecole',
  path: '/ecole',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConseillerRoute = AuthenticatedConseillerRouteImport.update({
  id: '/conseiller',
  path: '/conseiller',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedComptabiliteRoute =
  AuthenticatedComptabiliteRouteImport.update({
    id: '/comptabilite',
    path: '/comptabilite',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCommercialRoute = AuthenticatedCommercialRouteImport.update({
  id: '/commercial',
  path: '/commercial',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSecretaireIndexRoute =
  AuthenticatedSecretaireIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSecretaireRoute,
  } as any)
const AuthenticatedRhIndexRoute = AuthenticatedRhIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRhRoute,
} as any)
const AuthenticatedProjetsIndexRoute =
  AuthenticatedProjetsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjetsRoute,
  } as any)
const AuthenticatedEtudiantIndexRoute =
  AuthenticatedEtudiantIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEtudiantRoute,
  } as any)
const AuthenticatedEcoleIndexRoute = AuthenticatedEcoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedEcoleRoute,
} as any)
const AuthenticatedConseillerIndexRoute =
  AuthenticatedConseillerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedConseillerRoute,
  } as any)
const AuthenticatedComptabiliteIndexRoute =
  AuthenticatedComptabiliteIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedComptabiliteRoute,
  } as any)
const AuthenticatedCommercialIndexRoute =
  AuthenticatedCommercialIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCommercialRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedSecretaireValidationsRoute =
  AuthenticatedSecretaireValidationsRouteImport.update({
    id: '/validations',
    path: '/validations',
    getParentRoute: () => AuthenticatedSecretaireRoute,
  } as any)
const AuthenticatedSecretaireRendezVousRoute =
  AuthenticatedSecretaireRendezVousRouteImport.update({
    id: '/rendez-vous',
    path: '/rendez-vous',
    getParentRoute: () => AuthenticatedSecretaireRoute,
  } as any)
const AuthenticatedSecretaireMessagesRoute =
  AuthenticatedSecretaireMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedSecretaireRoute,
  } as any)
const AuthenticatedSecretaireEtudiantsRoute =
  AuthenticatedSecretaireEtudiantsRouteImport.update({
    id: '/etudiants',
    path: '/etudiants',
    getParentRoute: () => AuthenticatedSecretaireRoute,
  } as any)
const AuthenticatedSecretaireCourriersRoute =
  AuthenticatedSecretaireCourriersRouteImport.update({
    id: '/courriers',
    path: '/courriers',
    getParentRoute: () => AuthenticatedSecretaireRoute,
  } as any)
const AuthenticatedSecretaireClientsRoute =
  AuthenticatedSecretaireClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AuthenticatedSecretaireRoute,
  } as any)
const AuthenticatedRhRendezVousClientsRoute =
  AuthenticatedRhRendezVousClientsRouteImport.update({
    id: '/rendez-vous-clients',
    path: '/rendez-vous-clients',
    getParentRoute: () => AuthenticatedRhRoute,
  } as any)
const AuthenticatedRhPersonnelRoute =
  AuthenticatedRhPersonnelRouteImport.update({
    id: '/personnel',
    path: '/personnel',
    getParentRoute: () => AuthenticatedRhRoute,
  } as any)
const AuthenticatedProjetsRendezVousClientsRoute =
  AuthenticatedProjetsRendezVousClientsRouteImport.update({
    id: '/rendez-vous-clients',
    path: '/rendez-vous-clients',
    getParentRoute: () => AuthenticatedProjetsRoute,
  } as any)
const AuthenticatedProjetsListeRoute =
  AuthenticatedProjetsListeRouteImport.update({
    id: '/liste',
    path: '/liste',
    getParentRoute: () => AuthenticatedProjetsRoute,
  } as any)
const AuthenticatedEtudiantRendezVousRoute =
  AuthenticatedEtudiantRendezVousRouteImport.update({
    id: '/rendez-vous',
    path: '/rendez-vous',
    getParentRoute: () => AuthenticatedEtudiantRoute,
  } as any)
const AuthenticatedEtudiantProfilRoute =
  AuthenticatedEtudiantProfilRouteImport.update({
    id: '/profil',
    path: '/profil',
    getParentRoute: () => AuthenticatedEtudiantRoute,
  } as any)
const AuthenticatedEtudiantParcoursRoute =
  AuthenticatedEtudiantParcoursRouteImport.update({
    id: '/parcours',
    path: '/parcours',
    getParentRoute: () => AuthenticatedEtudiantRoute,
  } as any)
const AuthenticatedEtudiantMessagesRoute =
  AuthenticatedEtudiantMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedEtudiantRoute,
  } as any)
const AuthenticatedEtudiantEcolesRoute =
  AuthenticatedEtudiantEcolesRouteImport.update({
    id: '/ecoles',
    path: '/ecoles',
    getParentRoute: () => AuthenticatedEtudiantRoute,
  } as any)
const AuthenticatedEtudiantDossierRoute =
  AuthenticatedEtudiantDossierRouteImport.update({
    id: '/dossier',
    path: '/dossier',
    getParentRoute: () => AuthenticatedEtudiantRoute,
  } as any)
const AuthenticatedEtudiantDocumentsRoute =
  AuthenticatedEtudiantDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedEtudiantRoute,
  } as any)
const AuthenticatedEtudiantCandidaturesRoute =
  AuthenticatedEtudiantCandidaturesRouteImport.update({
    id: '/candidatures',
    path: '/candidatures',
    getParentRoute: () => AuthenticatedEtudiantRoute,
  } as any)
const AuthenticatedEcoleFormationsRoute =
  AuthenticatedEcoleFormationsRouteImport.update({
    id: '/formations',
    path: '/formations',
    getParentRoute: () => AuthenticatedEcoleRoute,
  } as any)
const AuthenticatedEcoleCandidatsRoute =
  AuthenticatedEcoleCandidatsRouteImport.update({
    id: '/candidats',
    path: '/candidats',
    getParentRoute: () => AuthenticatedEcoleRoute,
  } as any)
const AuthenticatedConseillerValidationsRoute =
  AuthenticatedConseillerValidationsRouteImport.update({
    id: '/validations',
    path: '/validations',
    getParentRoute: () => AuthenticatedConseillerRoute,
  } as any)
const AuthenticatedConseillerRendezVousClientsRoute =
  AuthenticatedConseillerRendezVousClientsRouteImport.update({
    id: '/rendez-vous-clients',
    path: '/rendez-vous-clients',
    getParentRoute: () => AuthenticatedConseillerRoute,
  } as any)
const AuthenticatedConseillerRendezVousRoute =
  AuthenticatedConseillerRendezVousRouteImport.update({
    id: '/rendez-vous',
    path: '/rendez-vous',
    getParentRoute: () => AuthenticatedConseillerRoute,
  } as any)
const AuthenticatedConseillerMessagesRoute =
  AuthenticatedConseillerMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedConseillerRoute,
  } as any)
const AuthenticatedConseillerEtudiantsRoute =
  AuthenticatedConseillerEtudiantsRouteImport.update({
    id: '/etudiants',
    path: '/etudiants',
    getParentRoute: () => AuthenticatedConseillerRoute,
  } as any)
const AuthenticatedComptabiliteTransactionsRoute =
  AuthenticatedComptabiliteTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedComptabiliteRoute,
  } as any)
const AuthenticatedComptabiliteRendezVousClientsRoute =
  AuthenticatedComptabiliteRendezVousClientsRouteImport.update({
    id: '/rendez-vous-clients',
    path: '/rendez-vous-clients',
    getParentRoute: () => AuthenticatedComptabiliteRoute,
  } as any)
const AuthenticatedCommercialRendezVousClientsRoute =
  AuthenticatedCommercialRendezVousClientsRouteImport.update({
    id: '/rendez-vous-clients',
    path: '/rendez-vous-clients',
    getParentRoute: () => AuthenticatedCommercialRoute,
  } as any)
const AuthenticatedCommercialActivitesRoute =
  AuthenticatedCommercialActivitesRouteImport.update({
    id: '/activites',
    path: '/activites',
    getParentRoute: () => AuthenticatedCommercialRoute,
  } as any)
const AuthenticatedAdminValidationsRoute =
  AuthenticatedAdminValidationsRouteImport.update({
    id: '/validations',
    path: '/validations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUtilisateursRoute =
  AuthenticatedAdminUtilisateursRouteImport.update({
    id: '/utilisateurs',
    path: '/utilisateurs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRendezVousClientsRoute =
  AuthenticatedAdminRendezVousClientsRouteImport.update({
    id: '/rendez-vous-clients',
    path: '/rendez-vous-clients',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRendezVousRoute =
  AuthenticatedAdminRendezVousRouteImport.update({
    id: '/rendez-vous',
    path: '/rendez-vous',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMessagesRoute =
  AuthenticatedAdminMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEcolesRoute =
  AuthenticatedAdminEcolesRouteImport.update({
    id: '/ecoles',
    path: '/ecoles',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDossiersRoute =
  AuthenticatedAdminDossiersRouteImport.update({
    id: '/dossiers',
    path: '/dossiers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedSecretaireEtudiantsIndexRoute =
  AuthenticatedSecretaireEtudiantsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSecretaireEtudiantsRoute,
  } as any)
const AuthenticatedConseillerEtudiantsIndexRoute =
  AuthenticatedConseillerEtudiantsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedConseillerEtudiantsRoute,
  } as any)
const AuthenticatedSecretaireEtudiantsStudentIdRoute =
  AuthenticatedSecretaireEtudiantsStudentIdRouteImport.update({
    id: '/$studentId',
    path: '/$studentId',
    getParentRoute: () => AuthenticatedSecretaireEtudiantsRoute,
  } as any)
const AuthenticatedConseillerEtudiantsStudentIdRoute =
  AuthenticatedConseillerEtudiantsStudentIdRouteImport.update({
    id: '/$studentId',
    path: '/$studentId',
    getParentRoute: () => AuthenticatedConseillerEtudiantsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blocked': typeof BlockedRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRoute
  '/commercial': typeof AuthenticatedCommercialRouteWithChildren
  '/comptabilite': typeof AuthenticatedComptabiliteRouteWithChildren
  '/conseiller': typeof AuthenticatedConseillerRouteWithChildren
  '/ecole': typeof AuthenticatedEcoleRouteWithChildren
  '/etudiant': typeof AuthenticatedEtudiantRouteWithChildren
  '/projets': typeof AuthenticatedProjetsRouteWithChildren
  '/rh': typeof AuthenticatedRhRouteWithChildren
  '/secretaire': typeof AuthenticatedSecretaireRouteWithChildren
  '/admin/dossiers': typeof AuthenticatedAdminDossiersRoute
  '/admin/ecoles': typeof AuthenticatedAdminEcolesRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/rendez-vous': typeof AuthenticatedAdminRendezVousRoute
  '/admin/rendez-vous-clients': typeof AuthenticatedAdminRendezVousClientsRoute
  '/admin/utilisateurs': typeof AuthenticatedAdminUtilisateursRoute
  '/admin/validations': typeof AuthenticatedAdminValidationsRoute
  '/commercial/activites': typeof AuthenticatedCommercialActivitesRoute
  '/commercial/rendez-vous-clients': typeof AuthenticatedCommercialRendezVousClientsRoute
  '/comptabilite/rendez-vous-clients': typeof AuthenticatedComptabiliteRendezVousClientsRoute
  '/comptabilite/transactions': typeof AuthenticatedComptabiliteTransactionsRoute
  '/conseiller/etudiants': typeof AuthenticatedConseillerEtudiantsRouteWithChildren
  '/conseiller/messages': typeof AuthenticatedConseillerMessagesRoute
  '/conseiller/rendez-vous': typeof AuthenticatedConseillerRendezVousRoute
  '/conseiller/rendez-vous-clients': typeof AuthenticatedConseillerRendezVousClientsRoute
  '/conseiller/validations': typeof AuthenticatedConseillerValidationsRoute
  '/ecole/candidats': typeof AuthenticatedEcoleCandidatsRoute
  '/ecole/formations': typeof AuthenticatedEcoleFormationsRoute
  '/etudiant/candidatures': typeof AuthenticatedEtudiantCandidaturesRoute
  '/etudiant/documents': typeof AuthenticatedEtudiantDocumentsRoute
  '/etudiant/dossier': typeof AuthenticatedEtudiantDossierRoute
  '/etudiant/ecoles': typeof AuthenticatedEtudiantEcolesRoute
  '/etudiant/messages': typeof AuthenticatedEtudiantMessagesRoute
  '/etudiant/parcours': typeof AuthenticatedEtudiantParcoursRoute
  '/etudiant/profil': typeof AuthenticatedEtudiantProfilRoute
  '/etudiant/rendez-vous': typeof AuthenticatedEtudiantRendezVousRoute
  '/projets/liste': typeof AuthenticatedProjetsListeRoute
  '/projets/rendez-vous-clients': typeof AuthenticatedProjetsRendezVousClientsRoute
  '/rh/personnel': typeof AuthenticatedRhPersonnelRoute
  '/rh/rendez-vous-clients': typeof AuthenticatedRhRendezVousClientsRoute
  '/secretaire/clients': typeof AuthenticatedSecretaireClientsRoute
  '/secretaire/courriers': typeof AuthenticatedSecretaireCourriersRoute
  '/secretaire/etudiants': typeof AuthenticatedSecretaireEtudiantsRouteWithChildren
  '/secretaire/messages': typeof AuthenticatedSecretaireMessagesRoute
  '/secretaire/rendez-vous': typeof AuthenticatedSecretaireRendezVousRoute
  '/secretaire/validations': typeof AuthenticatedSecretaireValidationsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/commercial/': typeof AuthenticatedCommercialIndexRoute
  '/comptabilite/': typeof AuthenticatedComptabiliteIndexRoute
  '/conseiller/': typeof AuthenticatedConseillerIndexRoute
  '/ecole/': typeof AuthenticatedEcoleIndexRoute
  '/etudiant/': typeof AuthenticatedEtudiantIndexRoute
  '/projets/': typeof AuthenticatedProjetsIndexRoute
  '/rh/': typeof AuthenticatedRhIndexRoute
  '/secretaire/': typeof AuthenticatedSecretaireIndexRoute
  '/conseiller/etudiants/$studentId': typeof AuthenticatedConseillerEtudiantsStudentIdRoute
  '/secretaire/etudiants/$studentId': typeof AuthenticatedSecretaireEtudiantsStudentIdRoute
  '/conseiller/etudiants/': typeof AuthenticatedConseillerEtudiantsIndexRoute
  '/secretaire/etudiants/': typeof AuthenticatedSecretaireEtudiantsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blocked': typeof BlockedRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/app': typeof AuthenticatedAppRoute
  '/admin/dossiers': typeof AuthenticatedAdminDossiersRoute
  '/admin/ecoles': typeof AuthenticatedAdminEcolesRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/rendez-vous': typeof AuthenticatedAdminRendezVousRoute
  '/admin/rendez-vous-clients': typeof AuthenticatedAdminRendezVousClientsRoute
  '/admin/utilisateurs': typeof AuthenticatedAdminUtilisateursRoute
  '/admin/validations': typeof AuthenticatedAdminValidationsRoute
  '/commercial/activites': typeof AuthenticatedCommercialActivitesRoute
  '/commercial/rendez-vous-clients': typeof AuthenticatedCommercialRendezVousClientsRoute
  '/comptabilite/rendez-vous-clients': typeof AuthenticatedComptabiliteRendezVousClientsRoute
  '/comptabilite/transactions': typeof AuthenticatedComptabiliteTransactionsRoute
  '/conseiller/messages': typeof AuthenticatedConseillerMessagesRoute
  '/conseiller/rendez-vous': typeof AuthenticatedConseillerRendezVousRoute
  '/conseiller/rendez-vous-clients': typeof AuthenticatedConseillerRendezVousClientsRoute
  '/conseiller/validations': typeof AuthenticatedConseillerValidationsRoute
  '/ecole/candidats': typeof AuthenticatedEcoleCandidatsRoute
  '/ecole/formations': typeof AuthenticatedEcoleFormationsRoute
  '/etudiant/candidatures': typeof AuthenticatedEtudiantCandidaturesRoute
  '/etudiant/documents': typeof AuthenticatedEtudiantDocumentsRoute
  '/etudiant/dossier': typeof AuthenticatedEtudiantDossierRoute
  '/etudiant/ecoles': typeof AuthenticatedEtudiantEcolesRoute
  '/etudiant/messages': typeof AuthenticatedEtudiantMessagesRoute
  '/etudiant/parcours': typeof AuthenticatedEtudiantParcoursRoute
  '/etudiant/profil': typeof AuthenticatedEtudiantProfilRoute
  '/etudiant/rendez-vous': typeof AuthenticatedEtudiantRendezVousRoute
  '/projets/liste': typeof AuthenticatedProjetsListeRoute
  '/projets/rendez-vous-clients': typeof AuthenticatedProjetsRendezVousClientsRoute
  '/rh/personnel': typeof AuthenticatedRhPersonnelRoute
  '/rh/rendez-vous-clients': typeof AuthenticatedRhRendezVousClientsRoute
  '/secretaire/clients': typeof AuthenticatedSecretaireClientsRoute
  '/secretaire/courriers': typeof AuthenticatedSecretaireCourriersRoute
  '/secretaire/messages': typeof AuthenticatedSecretaireMessagesRoute
  '/secretaire/rendez-vous': typeof AuthenticatedSecretaireRendezVousRoute
  '/secretaire/validations': typeof AuthenticatedSecretaireValidationsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/commercial': typeof AuthenticatedCommercialIndexRoute
  '/comptabilite': typeof AuthenticatedComptabiliteIndexRoute
  '/conseiller': typeof AuthenticatedConseillerIndexRoute
  '/ecole': typeof AuthenticatedEcoleIndexRoute
  '/etudiant': typeof AuthenticatedEtudiantIndexRoute
  '/projets': typeof AuthenticatedProjetsIndexRoute
  '/rh': typeof AuthenticatedRhIndexRoute
  '/secretaire': typeof AuthenticatedSecretaireIndexRoute
  '/conseiller/etudiants/$studentId': typeof AuthenticatedConseillerEtudiantsStudentIdRoute
  '/secretaire/etudiants/$studentId': typeof AuthenticatedSecretaireEtudiantsStudentIdRoute
  '/conseiller/etudiants': typeof AuthenticatedConseillerEtudiantsIndexRoute
  '/secretaire/etudiants': typeof AuthenticatedSecretaireEtudiantsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/blocked': typeof BlockedRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/commercial': typeof AuthenticatedCommercialRouteWithChildren
  '/_authenticated/comptabilite': typeof AuthenticatedComptabiliteRouteWithChildren
  '/_authenticated/conseiller': typeof AuthenticatedConseillerRouteWithChildren
  '/_authenticated/ecole': typeof AuthenticatedEcoleRouteWithChildren
  '/_authenticated/etudiant': typeof AuthenticatedEtudiantRouteWithChildren
  '/_authenticated/projets': typeof AuthenticatedProjetsRouteWithChildren
  '/_authenticated/rh': typeof AuthenticatedRhRouteWithChildren
  '/_authenticated/secretaire': typeof AuthenticatedSecretaireRouteWithChildren
  '/_authenticated/admin/dossiers': typeof AuthenticatedAdminDossiersRoute
  '/_authenticated/admin/ecoles': typeof AuthenticatedAdminEcolesRoute
  '/_authenticated/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/_authenticated/admin/rendez-vous': typeof AuthenticatedAdminRendezVousRoute
  '/_authenticated/admin/rendez-vous-clients': typeof AuthenticatedAdminRendezVousClientsRoute
  '/_authenticated/admin/utilisateurs': typeof AuthenticatedAdminUtilisateursRoute
  '/_authenticated/admin/validations': typeof AuthenticatedAdminValidationsRoute
  '/_authenticated/commercial/activites': typeof AuthenticatedCommercialActivitesRoute
  '/_authenticated/commercial/rendez-vous-clients': typeof AuthenticatedCommercialRendezVousClientsRoute
  '/_authenticated/comptabilite/rendez-vous-clients': typeof AuthenticatedComptabiliteRendezVousClientsRoute
  '/_authenticated/comptabilite/transactions': typeof AuthenticatedComptabiliteTransactionsRoute
  '/_authenticated/conseiller/etudiants': typeof AuthenticatedConseillerEtudiantsRouteWithChildren
  '/_authenticated/conseiller/messages': typeof AuthenticatedConseillerMessagesRoute
  '/_authenticated/conseiller/rendez-vous': typeof AuthenticatedConseillerRendezVousRoute
  '/_authenticated/conseiller/rendez-vous-clients': typeof AuthenticatedConseillerRendezVousClientsRoute
  '/_authenticated/conseiller/validations': typeof AuthenticatedConseillerValidationsRoute
  '/_authenticated/ecole/candidats': typeof AuthenticatedEcoleCandidatsRoute
  '/_authenticated/ecole/formations': typeof AuthenticatedEcoleFormationsRoute
  '/_authenticated/etudiant/candidatures': typeof AuthenticatedEtudiantCandidaturesRoute
  '/_authenticated/etudiant/documents': typeof AuthenticatedEtudiantDocumentsRoute
  '/_authenticated/etudiant/dossier': typeof AuthenticatedEtudiantDossierRoute
  '/_authenticated/etudiant/ecoles': typeof AuthenticatedEtudiantEcolesRoute
  '/_authenticated/etudiant/messages': typeof AuthenticatedEtudiantMessagesRoute
  '/_authenticated/etudiant/parcours': typeof AuthenticatedEtudiantParcoursRoute
  '/_authenticated/etudiant/profil': typeof AuthenticatedEtudiantProfilRoute
  '/_authenticated/etudiant/rendez-vous': typeof AuthenticatedEtudiantRendezVousRoute
  '/_authenticated/projets/liste': typeof AuthenticatedProjetsListeRoute
  '/_authenticated/projets/rendez-vous-clients': typeof AuthenticatedProjetsRendezVousClientsRoute
  '/_authenticated/rh/personnel': typeof AuthenticatedRhPersonnelRoute
  '/_authenticated/rh/rendez-vous-clients': typeof AuthenticatedRhRendezVousClientsRoute
  '/_authenticated/secretaire/clients': typeof AuthenticatedSecretaireClientsRoute
  '/_authenticated/secretaire/courriers': typeof AuthenticatedSecretaireCourriersRoute
  '/_authenticated/secretaire/etudiants': typeof AuthenticatedSecretaireEtudiantsRouteWithChildren
  '/_authenticated/secretaire/messages': typeof AuthenticatedSecretaireMessagesRoute
  '/_authenticated/secretaire/rendez-vous': typeof AuthenticatedSecretaireRendezVousRoute
  '/_authenticated/secretaire/validations': typeof AuthenticatedSecretaireValidationsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/commercial/': typeof AuthenticatedCommercialIndexRoute
  '/_authenticated/comptabilite/': typeof AuthenticatedComptabiliteIndexRoute
  '/_authenticated/conseiller/': typeof AuthenticatedConseillerIndexRoute
  '/_authenticated/ecole/': typeof AuthenticatedEcoleIndexRoute
  '/_authenticated/etudiant/': typeof AuthenticatedEtudiantIndexRoute
  '/_authenticated/projets/': typeof AuthenticatedProjetsIndexRoute
  '/_authenticated/rh/': typeof AuthenticatedRhIndexRoute
  '/_authenticated/secretaire/': typeof AuthenticatedSecretaireIndexRoute
  '/_authenticated/conseiller/etudiants/$studentId': typeof AuthenticatedConseillerEtudiantsStudentIdRoute
  '/_authenticated/secretaire/etudiants/$studentId': typeof AuthenticatedSecretaireEtudiantsStudentIdRoute
  '/_authenticated/conseiller/etudiants/': typeof AuthenticatedConseillerEtudiantsIndexRoute
  '/_authenticated/secretaire/etudiants/': typeof AuthenticatedSecretaireEtudiantsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blocked'
    | '/login'
    | '/unauthorized'
    | '/admin'
    | '/app'
    | '/commercial'
    | '/comptabilite'
    | '/conseiller'
    | '/ecole'
    | '/etudiant'
    | '/projets'
    | '/rh'
    | '/secretaire'
    | '/admin/dossiers'
    | '/admin/ecoles'
    | '/admin/messages'
    | '/admin/rendez-vous'
    | '/admin/rendez-vous-clients'
    | '/admin/utilisateurs'
    | '/admin/validations'
    | '/commercial/activites'
    | '/commercial/rendez-vous-clients'
    | '/comptabilite/rendez-vous-clients'
    | '/comptabilite/transactions'
    | '/conseiller/etudiants'
    | '/conseiller/messages'
    | '/conseiller/rendez-vous'
    | '/conseiller/rendez-vous-clients'
    | '/conseiller/validations'
    | '/ecole/candidats'
    | '/ecole/formations'
    | '/etudiant/candidatures'
    | '/etudiant/documents'
    | '/etudiant/dossier'
    | '/etudiant/ecoles'
    | '/etudiant/messages'
    | '/etudiant/parcours'
    | '/etudiant/profil'
    | '/etudiant/rendez-vous'
    | '/projets/liste'
    | '/projets/rendez-vous-clients'
    | '/rh/personnel'
    | '/rh/rendez-vous-clients'
    | '/secretaire/clients'
    | '/secretaire/courriers'
    | '/secretaire/etudiants'
    | '/secretaire/messages'
    | '/secretaire/rendez-vous'
    | '/secretaire/validations'
    | '/admin/'
    | '/commercial/'
    | '/comptabilite/'
    | '/conseiller/'
    | '/ecole/'
    | '/etudiant/'
    | '/projets/'
    | '/rh/'
    | '/secretaire/'
    | '/conseiller/etudiants/$studentId'
    | '/secretaire/etudiants/$studentId'
    | '/conseiller/etudiants/'
    | '/secretaire/etudiants/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blocked'
    | '/login'
    | '/unauthorized'
    | '/app'
    | '/admin/dossiers'
    | '/admin/ecoles'
    | '/admin/messages'
    | '/admin/rendez-vous'
    | '/admin/rendez-vous-clients'
    | '/admin/utilisateurs'
    | '/admin/validations'
    | '/commercial/activites'
    | '/commercial/rendez-vous-clients'
    | '/comptabilite/rendez-vous-clients'
    | '/comptabilite/transactions'
    | '/conseiller/messages'
    | '/conseiller/rendez-vous'
    | '/conseiller/rendez-vous-clients'
    | '/conseiller/validations'
    | '/ecole/candidats'
    | '/ecole/formations'
    | '/etudiant/candidatures'
    | '/etudiant/documents'
    | '/etudiant/dossier'
    | '/etudiant/ecoles'
    | '/etudiant/messages'
    | '/etudiant/parcours'
    | '/etudiant/profil'
    | '/etudiant/rendez-vous'
    | '/projets/liste'
    | '/projets/rendez-vous-clients'
    | '/rh/personnel'
    | '/rh/rendez-vous-clients'
    | '/secretaire/clients'
    | '/secretaire/courriers'
    | '/secretaire/messages'
    | '/secretaire/rendez-vous'
    | '/secretaire/validations'
    | '/admin'
    | '/commercial'
    | '/comptabilite'
    | '/conseiller'
    | '/ecole'
    | '/etudiant'
    | '/projets'
    | '/rh'
    | '/secretaire'
    | '/conseiller/etudiants/$studentId'
    | '/secretaire/etudiants/$studentId'
    | '/conseiller/etudiants'
    | '/secretaire/etudiants'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/blocked'
    | '/login'
    | '/unauthorized'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/commercial'
    | '/_authenticated/comptabilite'
    | '/_authenticated/conseiller'
    | '/_authenticated/ecole'
    | '/_authenticated/etudiant'
    | '/_authenticated/projets'
    | '/_authenticated/rh'
    | '/_authenticated/secretaire'
    | '/_authenticated/admin/dossiers'
    | '/_authenticated/admin/ecoles'
    | '/_authenticated/admin/messages'
    | '/_authenticated/admin/rendez-vous'
    | '/_authenticated/admin/rendez-vous-clients'
    | '/_authenticated/admin/utilisateurs'
    | '/_authenticated/admin/validations'
    | '/_authenticated/commercial/activites'
    | '/_authenticated/commercial/rendez-vous-clients'
    | '/_authenticated/comptabilite/rendez-vous-clients'
    | '/_authenticated/comptabilite/transactions'
    | '/_authenticated/conseiller/etudiants'
    | '/_authenticated/conseiller/messages'
    | '/_authenticated/conseiller/rendez-vous'
    | '/_authenticated/conseiller/rendez-vous-clients'
    | '/_authenticated/conseiller/validations'
    | '/_authenticated/ecole/candidats'
    | '/_authenticated/ecole/formations'
    | '/_authenticated/etudiant/candidatures'
    | '/_authenticated/etudiant/documents'
    | '/_authenticated/etudiant/dossier'
    | '/_authenticated/etudiant/ecoles'
    | '/_authenticated/etudiant/messages'
    | '/_authenticated/etudiant/parcours'
    | '/_authenticated/etudiant/profil'
    | '/_authenticated/etudiant/rendez-vous'
    | '/_authenticated/projets/liste'
    | '/_authenticated/projets/rendez-vous-clients'
    | '/_authenticated/rh/personnel'
    | '/_authenticated/rh/rendez-vous-clients'
    | '/_authenticated/secretaire/clients'
    | '/_authenticated/secretaire/courriers'
    | '/_authenticated/secretaire/etudiants'
    | '/_authenticated/secretaire/messages'
    | '/_authenticated/secretaire/rendez-vous'
    | '/_authenticated/secretaire/validations'
    | '/_authenticated/admin/'
    | '/_authenticated/commercial/'
    | '/_authenticated/comptabilite/'
    | '/_authenticated/conseiller/'
    | '/_authenticated/ecole/'
    | '/_authenticated/etudiant/'
    | '/_authenticated/projets/'
    | '/_authenticated/rh/'
    | '/_authenticated/secretaire/'
    | '/_authenticated/conseiller/etudiants/$studentId'
    | '/_authenticated/secretaire/etudiants/$studentId'
    | '/_authenticated/conseiller/etudiants/'
    | '/_authenticated/secretaire/etudiants/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  BlockedRoute: typeof BlockedRoute
  LoginRoute: typeof LoginRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocked': {
      id: '/blocked'
      path: '/blocked'
      fullPath: '/blocked'
      preLoaderRoute: typeof BlockedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/secretaire': {
      id: '/_authenticated/secretaire'
      path: '/secretaire'
      fullPath: '/secretaire'
      preLoaderRoute: typeof AuthenticatedSecretaireRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rh': {
      id: '/_authenticated/rh'
      path: '/rh'
      fullPath: '/rh'
      preLoaderRoute: typeof AuthenticatedRhRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projets': {
      id: '/_authenticated/projets'
      path: '/projets'
      fullPath: '/projets'
      preLoaderRoute: typeof AuthenticatedProjetsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/etudiant': {
      id: '/_authenticated/etudiant'
      path: '/etudiant'
      fullPath: '/etudiant'
      preLoaderRoute: typeof AuthenticatedEtudiantRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ecole': {
      id: '/_authenticated/ecole'
      path: '/ecole'
      fullPath: '/ecole'
      preLoaderRoute: typeof AuthenticatedEcoleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/conseiller': {
      id: '/_authenticated/conseiller'
      path: '/conseiller'
      fullPath: '/conseiller'
      preLoaderRoute: typeof AuthenticatedConseillerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/comptabilite': {
      id: '/_authenticated/comptabilite'
      path: '/comptabilite'
      fullPath: '/comptabilite'
      preLoaderRoute: typeof AuthenticatedComptabiliteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/commercial': {
      id: '/_authenticated/commercial'
      path: '/commercial'
      fullPath: '/commercial'
      preLoaderRoute: typeof AuthenticatedCommercialRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/secretaire/': {
      id: '/_authenticated/secretaire/'
      path: '/'
      fullPath: '/secretaire/'
      preLoaderRoute: typeof AuthenticatedSecretaireIndexRouteImport
      parentRoute: typeof AuthenticatedSecretaireRoute
    }
    '/_authenticated/rh/': {
      id: '/_authenticated/rh/'
      path: '/'
      fullPath: '/rh/'
      preLoaderRoute: typeof AuthenticatedRhIndexRouteImport
      parentRoute: typeof AuthenticatedRhRoute
    }
    '/_authenticated/projets/': {
      id: '/_authenticated/projets/'
      path: '/'
      fullPath: '/projets/'
      preLoaderRoute: typeof AuthenticatedProjetsIndexRouteImport
      parentRoute: typeof AuthenticatedProjetsRoute
    }
    '/_authenticated/etudiant/': {
      id: '/_authenticated/etudiant/'
      path: '/'
      fullPath: '/etudiant/'
      preLoaderRoute: typeof AuthenticatedEtudiantIndexRouteImport
      parentRoute: typeof AuthenticatedEtudiantRoute
    }
    '/_authenticated/ecole/': {
      id: '/_authenticated/ecole/'
      path: '/'
      fullPath: '/ecole/'
      preLoaderRoute: typeof AuthenticatedEcoleIndexRouteImport
      parentRoute: typeof AuthenticatedEcoleRoute
    }
    '/_authenticated/conseiller/': {
      id: '/_authenticated/conseiller/'
      path: '/'
      fullPath: '/conseiller/'
      preLoaderRoute: typeof AuthenticatedConseillerIndexRouteImport
      parentRoute: typeof AuthenticatedConseillerRoute
    }
    '/_authenticated/comptabilite/': {
      id: '/_authenticated/comptabilite/'
      path: '/'
      fullPath: '/comptabilite/'
      preLoaderRoute: typeof AuthenticatedComptabiliteIndexRouteImport
      parentRoute: typeof AuthenticatedComptabiliteRoute
    }
    '/_authenticated/commercial/': {
      id: '/_authenticated/commercial/'
      path: '/'
      fullPath: '/commercial/'
      preLoaderRoute: typeof AuthenticatedCommercialIndexRouteImport
      parentRoute: typeof AuthenticatedCommercialRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/secretaire/validations': {
      id: '/_authenticated/secretaire/validations'
      path: '/validations'
      fullPath: '/secretaire/validations'
      preLoaderRoute: typeof AuthenticatedSecretaireValidationsRouteImport
      parentRoute: typeof AuthenticatedSecretaireRoute
    }
    '/_authenticated/secretaire/rendez-vous': {
      id: '/_authenticated/secretaire/rendez-vous'
      path: '/rendez-vous'
      fullPath: '/secretaire/rendez-vous'
      preLoaderRoute: typeof AuthenticatedSecretaireRendezVousRouteImport
      parentRoute: typeof AuthenticatedSecretaireRoute
    }
    '/_authenticated/secretaire/messages': {
      id: '/_authenticated/secretaire/messages'
      path: '/messages'
      fullPath: '/secretaire/messages'
      preLoaderRoute: typeof AuthenticatedSecretaireMessagesRouteImport
      parentRoute: typeof AuthenticatedSecretaireRoute
    }
    '/_authenticated/secretaire/etudiants': {
      id: '/_authenticated/secretaire/etudiants'
      path: '/etudiants'
      fullPath: '/secretaire/etudiants'
      preLoaderRoute: typeof AuthenticatedSecretaireEtudiantsRouteImport
      parentRoute: typeof AuthenticatedSecretaireRoute
    }
    '/_authenticated/secretaire/courriers': {
      id: '/_authenticated/secretaire/courriers'
      path: '/courriers'
      fullPath: '/secretaire/courriers'
      preLoaderRoute: typeof AuthenticatedSecretaireCourriersRouteImport
      parentRoute: typeof AuthenticatedSecretaireRoute
    }
    '/_authenticated/secretaire/clients': {
      id: '/_authenticated/secretaire/clients'
      path: '/clients'
      fullPath: '/secretaire/clients'
      preLoaderRoute: typeof AuthenticatedSecretaireClientsRouteImport
      parentRoute: typeof AuthenticatedSecretaireRoute
    }
    '/_authenticated/rh/rendez-vous-clients': {
      id: '/_authenticated/rh/rendez-vous-clients'
      path: '/rendez-vous-clients'
      fullPath: '/rh/rendez-vous-clients'
      preLoaderRoute: typeof AuthenticatedRhRendezVousClientsRouteImport
      parentRoute: typeof AuthenticatedRhRoute
    }
    '/_authenticated/rh/personnel': {
      id: '/_authenticated/rh/personnel'
      path: '/personnel'
      fullPath: '/rh/personnel'
      preLoaderRoute: typeof AuthenticatedRhPersonnelRouteImport
      parentRoute: typeof AuthenticatedRhRoute
    }
    '/_authenticated/projets/rendez-vous-clients': {
      id: '/_authenticated/projets/rendez-vous-clients'
      path: '/rendez-vous-clients'
      fullPath: '/projets/rendez-vous-clients'
      preLoaderRoute: typeof AuthenticatedProjetsRendezVousClientsRouteImport
      parentRoute: typeof AuthenticatedProjetsRoute
    }
    '/_authenticated/projets/liste': {
      id: '/_authenticated/projets/liste'
      path: '/liste'
      fullPath: '/projets/liste'
      preLoaderRoute: typeof AuthenticatedProjetsListeRouteImport
      parentRoute: typeof AuthenticatedProjetsRoute
    }
    '/_authenticated/etudiant/rendez-vous': {
      id: '/_authenticated/etudiant/rendez-vous'
      path: '/rendez-vous'
      fullPath: '/etudiant/rendez-vous'
      preLoaderRoute: typeof AuthenticatedEtudiantRendezVousRouteImport
      parentRoute: typeof AuthenticatedEtudiantRoute
    }
    '/_authenticated/etudiant/profil': {
      id: '/_authenticated/etudiant/profil'
      path: '/profil'
      fullPath: '/etudiant/profil'
      preLoaderRoute: typeof AuthenticatedEtudiantProfilRouteImport
      parentRoute: typeof AuthenticatedEtudiantRoute
    }
    '/_authenticated/etudiant/parcours': {
      id: '/_authenticated/etudiant/parcours'
      path: '/parcours'
      fullPath: '/etudiant/parcours'
      preLoaderRoute: typeof AuthenticatedEtudiantParcoursRouteImport
      parentRoute: typeof AuthenticatedEtudiantRoute
    }
    '/_authenticated/etudiant/messages': {
      id: '/_authenticated/etudiant/messages'
      path: '/messages'
      fullPath: '/etudiant/messages'
      preLoaderRoute: typeof AuthenticatedEtudiantMessagesRouteImport
      parentRoute: typeof AuthenticatedEtudiantRoute
    }
    '/_authenticated/etudiant/ecoles': {
      id: '/_authenticated/etudiant/ecoles'
      path: '/ecoles'
      fullPath: '/etudiant/ecoles'
      preLoaderRoute: typeof AuthenticatedEtudiantEcolesRouteImport
      parentRoute: typeof AuthenticatedEtudiantRoute
    }
    '/_authenticated/etudiant/dossier': {
      id: '/_authenticated/etudiant/dossier'
      path: '/dossier'
      fullPath: '/etudiant/dossier'
      preLoaderRoute: typeof AuthenticatedEtudiantDossierRouteImport
      parentRoute: typeof AuthenticatedEtudiantRoute
    }
    '/_authenticated/etudiant/documents': {
      id: '/_authenticated/etudiant/documents'
      path: '/documents'
      fullPath: '/etudiant/documents'
      preLoaderRoute: typeof AuthenticatedEtudiantDocumentsRouteImport
      parentRoute: typeof AuthenticatedEtudiantRoute
    }
    '/_authenticated/etudiant/candidatures': {
      id: '/_authenticated/etudiant/candidatures'
      path: '/candidatures'
      fullPath: '/etudiant/candidatures'
      preLoaderRoute: typeof AuthenticatedEtudiantCandidaturesRouteImport
      parentRoute: typeof AuthenticatedEtudiantRoute
    }
    '/_authenticated/ecole/formations': {
      id: '/_authenticated/ecole/formations'
      path: '/formations'
      fullPath: '/ecole/formations'
      preLoaderRoute: typeof AuthenticatedEcoleFormationsRouteImport
      parentRoute: typeof AuthenticatedEcoleRoute
    }
    '/_authenticated/ecole/candidats': {
      id: '/_authenticated/ecole/candidats'
      path: '/candidats'
      fullPath: '/ecole/candidats'
      preLoaderRoute: typeof AuthenticatedEcoleCandidatsRouteImport
      parentRoute: typeof AuthenticatedEcoleRoute
    }
    '/_authenticated/conseiller/validations': {
      id: '/_authenticated/conseiller/validations'
      path: '/validations'
      fullPath: '/conseiller/validations'
      preLoaderRoute: typeof AuthenticatedConseillerValidationsRouteImport
      parentRoute: typeof AuthenticatedConseillerRoute
    }
    '/_authenticated/conseiller/rendez-vous-clients': {
      id: '/_authenticated/conseiller/rendez-vous-clients'
      path: '/rendez-vous-clients'
      fullPath: '/conseiller/rendez-vous-clients'
      preLoaderRoute: typeof AuthenticatedConseillerRendezVousClientsRouteImport
      parentRoute: typeof AuthenticatedConseillerRoute
    }
    '/_authenticated/conseiller/rendez-vous': {
      id: '/_authenticated/conseiller/rendez-vous'
      path: '/rendez-vous'
      fullPath: '/conseiller/rendez-vous'
      preLoaderRoute: typeof AuthenticatedConseillerRendezVousRouteImport
      parentRoute: typeof AuthenticatedConseillerRoute
    }
    '/_authenticated/conseiller/messages': {
      id: '/_authenticated/conseiller/messages'
      path: '/messages'
      fullPath: '/conseiller/messages'
      preLoaderRoute: typeof AuthenticatedConseillerMessagesRouteImport
      parentRoute: typeof AuthenticatedConseillerRoute
    }
    '/_authenticated/conseiller/etudiants': {
      id: '/_authenticated/conseiller/etudiants'
      path: '/etudiants'
      fullPath: '/conseiller/etudiants'
      preLoaderRoute: typeof AuthenticatedConseillerEtudiantsRouteImport
      parentRoute: typeof AuthenticatedConseillerRoute
    }
    '/_authenticated/comptabilite/transactions': {
      id: '/_authenticated/comptabilite/transactions'
      path: '/transactions'
      fullPath: '/comptabilite/transactions'
      preLoaderRoute: typeof AuthenticatedComptabiliteTransactionsRouteImport
      parentRoute: typeof AuthenticatedComptabiliteRoute
    }
    '/_authenticated/comptabilite/rendez-vous-clients': {
      id: '/_authenticated/comptabilite/rendez-vous-clients'
      path: '/rendez-vous-clients'
      fullPath: '/comptabilite/rendez-vous-clients'
      preLoaderRoute: typeof AuthenticatedComptabiliteRendezVousClientsRouteImport
      parentRoute: typeof AuthenticatedComptabiliteRoute
    }
    '/_authenticated/commercial/rendez-vous-clients': {
      id: '/_authenticated/commercial/rendez-vous-clients'
      path: '/rendez-vous-clients'
      fullPath: '/commercial/rendez-vous-clients'
      preLoaderRoute: typeof AuthenticatedCommercialRendezVousClientsRouteImport
      parentRoute: typeof AuthenticatedCommercialRoute
    }
    '/_authenticated/commercial/activites': {
      id: '/_authenticated/commercial/activites'
      path: '/activites'
      fullPath: '/commercial/activites'
      preLoaderRoute: typeof AuthenticatedCommercialActivitesRouteImport
      parentRoute: typeof AuthenticatedCommercialRoute
    }
    '/_authenticated/admin/validations': {
      id: '/_authenticated/admin/validations'
      path: '/validations'
      fullPath: '/admin/validations'
      preLoaderRoute: typeof AuthenticatedAdminValidationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/utilisateurs': {
      id: '/_authenticated/admin/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/admin/utilisateurs'
      preLoaderRoute: typeof AuthenticatedAdminUtilisateursRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/rendez-vous-clients': {
      id: '/_authenticated/admin/rendez-vous-clients'
      path: '/rendez-vous-clients'
      fullPath: '/admin/rendez-vous-clients'
      preLoaderRoute: typeof AuthenticatedAdminRendezVousClientsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/rendez-vous': {
      id: '/_authenticated/admin/rendez-vous'
      path: '/rendez-vous'
      fullPath: '/admin/rendez-vous'
      preLoaderRoute: typeof AuthenticatedAdminRendezVousRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/messages': {
      id: '/_authenticated/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AuthenticatedAdminMessagesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ecoles': {
      id: '/_authenticated/admin/ecoles'
      path: '/ecoles'
      fullPath: '/admin/ecoles'
      preLoaderRoute: typeof AuthenticatedAdminEcolesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dossiers': {
      id: '/_authenticated/admin/dossiers'
      path: '/dossiers'
      fullPath: '/admin/dossiers'
      preLoaderRoute: typeof AuthenticatedAdminDossiersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/secretaire/etudiants/': {
      id: '/_authenticated/secretaire/etudiants/'
      path: '/'
      fullPath: '/secretaire/etudiants/'
      preLoaderRoute: typeof AuthenticatedSecretaireEtudiantsIndexRouteImport
      parentRoute: typeof AuthenticatedSecretaireEtudiantsRoute
    }
    '/_authenticated/conseiller/etudiants/': {
      id: '/_authenticated/conseiller/etudiants/'
      path: '/'
      fullPath: '/conseiller/etudiants/'
      preLoaderRoute: typeof AuthenticatedConseillerEtudiantsIndexRouteImport
      parentRoute: typeof AuthenticatedConseillerEtudiantsRoute
    }
    '/_authenticated/secretaire/etudiants/$studentId': {
      id: '/_authenticated/secretaire/etudiants/$studentId'
      path: '/$studentId'
      fullPath: '/secretaire/etudiants/$studentId'
      preLoaderRoute: typeof AuthenticatedSecretaireEtudiantsStudentIdRouteImport
      parentRoute: typeof AuthenticatedSecretaireEtudiantsRoute
    }
    '/_authenticated/conseiller/etudiants/$studentId': {
      id: '/_authenticated/conseiller/etudiants/$studentId'
      path: '/$studentId'
      fullPath: '/conseiller/etudiants/$studentId'
      preLoaderRoute: typeof AuthenticatedConseillerEtudiantsStudentIdRouteImport
      parentRoute: typeof AuthenticatedConseillerEtudiantsRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminDossiersRoute: typeof AuthenticatedAdminDossiersRoute
  AuthenticatedAdminEcolesRoute: typeof AuthenticatedAdminEcolesRoute
  AuthenticatedAdminMessagesRoute: typeof AuthenticatedAdminMessagesRoute
  AuthenticatedAdminRendezVousRoute: typeof AuthenticatedAdminRendezVousRoute
  AuthenticatedAdminRendezVousClientsRoute: typeof AuthenticatedAdminRendezVousClientsRoute
  AuthenticatedAdminUtilisateursRoute: typeof AuthenticatedAdminUtilisateursRoute
  AuthenticatedAdminValidationsRoute: typeof AuthenticatedAdminValidationsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminDossiersRoute: AuthenticatedAdminDossiersRoute,
  AuthenticatedAdminEcolesRoute: AuthenticatedAdminEcolesRoute,
  AuthenticatedAdminMessagesRoute: AuthenticatedAdminMessagesRoute,
  AuthenticatedAdminRendezVousRoute: AuthenticatedAdminRendezVousRoute,
  AuthenticatedAdminRendezVousClientsRoute:
    AuthenticatedAdminRendezVousClientsRoute,
  AuthenticatedAdminUtilisateursRoute: AuthenticatedAdminUtilisateursRoute,
  AuthenticatedAdminValidationsRoute: AuthenticatedAdminValidationsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedCommercialRouteChildren {
  AuthenticatedCommercialActivitesRoute: typeof AuthenticatedCommercialActivitesRoute
  AuthenticatedCommercialRendezVousClientsRoute: typeof AuthenticatedCommercialRendezVousClientsRoute
  AuthenticatedCommercialIndexRoute: typeof AuthenticatedCommercialIndexRoute
}

const AuthenticatedCommercialRouteChildren: AuthenticatedCommercialRouteChildren =
  {
    AuthenticatedCommercialActivitesRoute:
      AuthenticatedCommercialActivitesRoute,
    AuthenticatedCommercialRendezVousClientsRoute:
      AuthenticatedCommercialRendezVousClientsRoute,
    AuthenticatedCommercialIndexRoute: AuthenticatedCommercialIndexRoute,
  }

const AuthenticatedCommercialRouteWithChildren =
  AuthenticatedCommercialRoute._addFileChildren(
    AuthenticatedCommercialRouteChildren,
  )

interface AuthenticatedComptabiliteRouteChildren {
  AuthenticatedComptabiliteRendezVousClientsRoute: typeof AuthenticatedComptabiliteRendezVousClientsRoute
  AuthenticatedComptabiliteTransactionsRoute: typeof AuthenticatedComptabiliteTransactionsRoute
  AuthenticatedComptabiliteIndexRoute: typeof AuthenticatedComptabiliteIndexRoute
}

const AuthenticatedComptabiliteRouteChildren: AuthenticatedComptabiliteRouteChildren =
  {
    AuthenticatedComptabiliteRendezVousClientsRoute:
      AuthenticatedComptabiliteRendezVousClientsRoute,
    AuthenticatedComptabiliteTransactionsRoute:
      AuthenticatedComptabiliteTransactionsRoute,
    AuthenticatedComptabiliteIndexRoute: AuthenticatedComptabiliteIndexRoute,
  }

const AuthenticatedComptabiliteRouteWithChildren =
  AuthenticatedComptabiliteRoute._addFileChildren(
    AuthenticatedComptabiliteRouteChildren,
  )

interface AuthenticatedConseillerEtudiantsRouteChildren {
  AuthenticatedConseillerEtudiantsStudentIdRoute: typeof AuthenticatedConseillerEtudiantsStudentIdRoute
  AuthenticatedConseillerEtudiantsIndexRoute: typeof AuthenticatedConseillerEtudiantsIndexRoute
}

const AuthenticatedConseillerEtudiantsRouteChildren: AuthenticatedConseillerEtudiantsRouteChildren =
  {
    AuthenticatedConseillerEtudiantsStudentIdRoute:
      AuthenticatedConseillerEtudiantsStudentIdRoute,
    AuthenticatedConseillerEtudiantsIndexRoute:
      AuthenticatedConseillerEtudiantsIndexRoute,
  }

const AuthenticatedConseillerEtudiantsRouteWithChildren =
  AuthenticatedConseillerEtudiantsRoute._addFileChildren(
    AuthenticatedConseillerEtudiantsRouteChildren,
  )

interface AuthenticatedConseillerRouteChildren {
  AuthenticatedConseillerEtudiantsRoute: typeof AuthenticatedConseillerEtudiantsRouteWithChildren
  AuthenticatedConseillerMessagesRoute: typeof AuthenticatedConseillerMessagesRoute
  AuthenticatedConseillerRendezVousRoute: typeof AuthenticatedConseillerRendezVousRoute
  AuthenticatedConseillerRendezVousClientsRoute: typeof AuthenticatedConseillerRendezVousClientsRoute
  AuthenticatedConseillerValidationsRoute: typeof AuthenticatedConseillerValidationsRoute
  AuthenticatedConseillerIndexRoute: typeof AuthenticatedConseillerIndexRoute
}

const AuthenticatedConseillerRouteChildren: AuthenticatedConseillerRouteChildren =
  {
    AuthenticatedConseillerEtudiantsRoute:
      AuthenticatedConseillerEtudiantsRouteWithChildren,
    AuthenticatedConseillerMessagesRoute: AuthenticatedConseillerMessagesRoute,
    AuthenticatedConseillerRendezVousRoute:
      AuthenticatedConseillerRendezVousRoute,
    AuthenticatedConseillerRendezVousClientsRoute:
      AuthenticatedConseillerRendezVousClientsRoute,
    AuthenticatedConseillerValidationsRoute:
      AuthenticatedConseillerValidationsRoute,
    AuthenticatedConseillerIndexRoute: AuthenticatedConseillerIndexRoute,
  }

const AuthenticatedConseillerRouteWithChildren =
  AuthenticatedConseillerRoute._addFileChildren(
    AuthenticatedConseillerRouteChildren,
  )

interface AuthenticatedEcoleRouteChildren {
  AuthenticatedEcoleCandidatsRoute: typeof AuthenticatedEcoleCandidatsRoute
  AuthenticatedEcoleFormationsRoute: typeof AuthenticatedEcoleFormationsRoute
  AuthenticatedEcoleIndexRoute: typeof AuthenticatedEcoleIndexRoute
}

const AuthenticatedEcoleRouteChildren: AuthenticatedEcoleRouteChildren = {
  AuthenticatedEcoleCandidatsRoute: AuthenticatedEcoleCandidatsRoute,
  AuthenticatedEcoleFormationsRoute: AuthenticatedEcoleFormationsRoute,
  AuthenticatedEcoleIndexRoute: AuthenticatedEcoleIndexRoute,
}

const AuthenticatedEcoleRouteWithChildren =
  AuthenticatedEcoleRoute._addFileChildren(AuthenticatedEcoleRouteChildren)

interface AuthenticatedEtudiantRouteChildren {
  AuthenticatedEtudiantCandidaturesRoute: typeof AuthenticatedEtudiantCandidaturesRoute
  AuthenticatedEtudiantDocumentsRoute: typeof AuthenticatedEtudiantDocumentsRoute
  AuthenticatedEtudiantDossierRoute: typeof AuthenticatedEtudiantDossierRoute
  AuthenticatedEtudiantEcolesRoute: typeof AuthenticatedEtudiantEcolesRoute
  AuthenticatedEtudiantMessagesRoute: typeof AuthenticatedEtudiantMessagesRoute
  AuthenticatedEtudiantParcoursRoute: typeof AuthenticatedEtudiantParcoursRoute
  AuthenticatedEtudiantProfilRoute: typeof AuthenticatedEtudiantProfilRoute
  AuthenticatedEtudiantRendezVousRoute: typeof AuthenticatedEtudiantRendezVousRoute
  AuthenticatedEtudiantIndexRoute: typeof AuthenticatedEtudiantIndexRoute
}

const AuthenticatedEtudiantRouteChildren: AuthenticatedEtudiantRouteChildren = {
  AuthenticatedEtudiantCandidaturesRoute:
    AuthenticatedEtudiantCandidaturesRoute,
  AuthenticatedEtudiantDocumentsRoute: AuthenticatedEtudiantDocumentsRoute,
  AuthenticatedEtudiantDossierRoute: AuthenticatedEtudiantDossierRoute,
  AuthenticatedEtudiantEcolesRoute: AuthenticatedEtudiantEcolesRoute,
  AuthenticatedEtudiantMessagesRoute: AuthenticatedEtudiantMessagesRoute,
  AuthenticatedEtudiantParcoursRoute: AuthenticatedEtudiantParcoursRoute,
  AuthenticatedEtudiantProfilRoute: AuthenticatedEtudiantProfilRoute,
  AuthenticatedEtudiantRendezVousRoute: AuthenticatedEtudiantRendezVousRoute,
  AuthenticatedEtudiantIndexRoute: AuthenticatedEtudiantIndexRoute,
}

const AuthenticatedEtudiantRouteWithChildren =
  AuthenticatedEtudiantRoute._addFileChildren(
    AuthenticatedEtudiantRouteChildren,
  )

interface AuthenticatedProjetsRouteChildren {
  AuthenticatedProjetsListeRoute: typeof AuthenticatedProjetsListeRoute
  AuthenticatedProjetsRendezVousClientsRoute: typeof AuthenticatedProjetsRendezVousClientsRoute
  AuthenticatedProjetsIndexRoute: typeof AuthenticatedProjetsIndexRoute
}

const AuthenticatedProjetsRouteChildren: AuthenticatedProjetsRouteChildren = {
  AuthenticatedProjetsListeRoute: AuthenticatedProjetsListeRoute,
  AuthenticatedProjetsRendezVousClientsRoute:
    AuthenticatedProjetsRendezVousClientsRoute,
  AuthenticatedProjetsIndexRoute: AuthenticatedProjetsIndexRoute,
}

const AuthenticatedProjetsRouteWithChildren =
  AuthenticatedProjetsRoute._addFileChildren(AuthenticatedProjetsRouteChildren)

interface AuthenticatedRhRouteChildren {
  AuthenticatedRhPersonnelRoute: typeof AuthenticatedRhPersonnelRoute
  AuthenticatedRhRendezVousClientsRoute: typeof AuthenticatedRhRendezVousClientsRoute
  AuthenticatedRhIndexRoute: typeof AuthenticatedRhIndexRoute
}

const AuthenticatedRhRouteChildren: AuthenticatedRhRouteChildren = {
  AuthenticatedRhPersonnelRoute: AuthenticatedRhPersonnelRoute,
  AuthenticatedRhRendezVousClientsRoute: AuthenticatedRhRendezVousClientsRoute,
  AuthenticatedRhIndexRoute: AuthenticatedRhIndexRoute,
}

const AuthenticatedRhRouteWithChildren = AuthenticatedRhRoute._addFileChildren(
  AuthenticatedRhRouteChildren,
)

interface AuthenticatedSecretaireEtudiantsRouteChildren {
  AuthenticatedSecretaireEtudiantsStudentIdRoute: typeof AuthenticatedSecretaireEtudiantsStudentIdRoute
  AuthenticatedSecretaireEtudiantsIndexRoute: typeof AuthenticatedSecretaireEtudiantsIndexRoute
}

const AuthenticatedSecretaireEtudiantsRouteChildren: AuthenticatedSecretaireEtudiantsRouteChildren =
  {
    AuthenticatedSecretaireEtudiantsStudentIdRoute:
      AuthenticatedSecretaireEtudiantsStudentIdRoute,
    AuthenticatedSecretaireEtudiantsIndexRoute:
      AuthenticatedSecretaireEtudiantsIndexRoute,
  }

const AuthenticatedSecretaireEtudiantsRouteWithChildren =
  AuthenticatedSecretaireEtudiantsRoute._addFileChildren(
    AuthenticatedSecretaireEtudiantsRouteChildren,
  )

interface AuthenticatedSecretaireRouteChildren {
  AuthenticatedSecretaireClientsRoute: typeof AuthenticatedSecretaireClientsRoute
  AuthenticatedSecretaireCourriersRoute: typeof AuthenticatedSecretaireCourriersRoute
  AuthenticatedSecretaireEtudiantsRoute: typeof AuthenticatedSecretaireEtudiantsRouteWithChildren
  AuthenticatedSecretaireMessagesRoute: typeof AuthenticatedSecretaireMessagesRoute
  AuthenticatedSecretaireRendezVousRoute: typeof AuthenticatedSecretaireRendezVousRoute
  AuthenticatedSecretaireValidationsRoute: typeof AuthenticatedSecretaireValidationsRoute
  AuthenticatedSecretaireIndexRoute: typeof AuthenticatedSecretaireIndexRoute
}

const AuthenticatedSecretaireRouteChildren: AuthenticatedSecretaireRouteChildren =
  {
    AuthenticatedSecretaireClientsRoute: AuthenticatedSecretaireClientsRoute,
    AuthenticatedSecretaireCourriersRoute:
      AuthenticatedSecretaireCourriersRoute,
    AuthenticatedSecretaireEtudiantsRoute:
      AuthenticatedSecretaireEtudiantsRouteWithChildren,
    AuthenticatedSecretaireMessagesRoute: AuthenticatedSecretaireMessagesRoute,
    AuthenticatedSecretaireRendezVousRoute:
      AuthenticatedSecretaireRendezVousRoute,
    AuthenticatedSecretaireValidationsRoute:
      AuthenticatedSecretaireValidationsRoute,
    AuthenticatedSecretaireIndexRoute: AuthenticatedSecretaireIndexRoute,
  }

const AuthenticatedSecretaireRouteWithChildren =
  AuthenticatedSecretaireRoute._addFileChildren(
    AuthenticatedSecretaireRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedCommercialRoute: typeof AuthenticatedCommercialRouteWithChildren
  AuthenticatedComptabiliteRoute: typeof AuthenticatedComptabiliteRouteWithChildren
  AuthenticatedConseillerRoute: typeof AuthenticatedConseillerRouteWithChildren
  AuthenticatedEcoleRoute: typeof AuthenticatedEcoleRouteWithChildren
  AuthenticatedEtudiantRoute: typeof AuthenticatedEtudiantRouteWithChildren
  AuthenticatedProjetsRoute: typeof AuthenticatedProjetsRouteWithChildren
  AuthenticatedRhRoute: typeof AuthenticatedRhRouteWithChildren
  AuthenticatedSecretaireRoute: typeof AuthenticatedSecretaireRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedCommercialRoute: AuthenticatedCommercialRouteWithChildren,
  AuthenticatedComptabiliteRoute: AuthenticatedComptabiliteRouteWithChildren,
  AuthenticatedConseillerRoute: AuthenticatedConseillerRouteWithChildren,
  AuthenticatedEcoleRoute: AuthenticatedEcoleRouteWithChildren,
  AuthenticatedEtudiantRoute: AuthenticatedEtudiantRouteWithChildren,
  AuthenticatedProjetsRoute: AuthenticatedProjetsRouteWithChildren,
  AuthenticatedRhRoute: AuthenticatedRhRouteWithChildren,
  AuthenticatedSecretaireRoute: AuthenticatedSecretaireRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  BlockedRoute: BlockedRoute,
  LoginRoute: LoginRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
